### ISSUE TITLE
web3 直播 - hackusama 参赛

### ISSUE THREAD

**Issue by jimmychu0807** [subdarkdex/subdex-chain#4]
@fyang1024 @iorveth @KStasi @herryho @whalelephant

你们好，我是 Jimmy。是 Parity 亚洲团队的工程师，也负责开发社区的推广。我们打算对亚洲区 hackusama 参赛得奖团队作约15-20分钟的直播访谈。而你们是其中一队我们想约做访谈的。你们会有兴趣参与吗？

是的话，请加我微信确认：**jimmychu0807**

Hi, this is Jimmy. I am a runtime engineer in Parity Asia team, and also responsible for building our developer community in Asia. We would like to conduct a 15 - 20 mins interview with teams who have won in the Hackusama, and you are one of the teams interested talking to. The interview will be streamed on our Crowdcast and Bilibili site. Would you be interested to participate in the interview?

If yes, please add my wechat to confirm: **jimmychu0807**

---
### 詳情 Details

时间 Time：10月9日 18:00 - 19:00 (UTC +8)  / Oct 9th 18:00 - 19:00 (UTC +8)
软件 Software： Zoom
使用语言 Language：主要中文，但用英文也可以 / Mainly Chinese, but feel free to use English as well

主要问题 / Questions：
- 为什么参加这次 Hackusama?  / Why did you participate in this Hackusama?
- 参赛作品理念是什么？为何有这个构思? / What is the idea behind your project? What motivate you on this?
- 这次参赛作品会有后续发展吗？ / Would there be any further development on the project after the hackathon?
- 这次使用 Substrate 及其生态的工具来做开发感觉怎么样？什么地方好，什么地方有待提高？ / After building a project in Substrate ecosystem, what do you think about? What do you like? What do you hope to improve?

**Comment by fyang1024** [comment]
Thank you @jimmychu0807 for the invitation. I've added your WeChat. I believe @herryho also has added your WeChat.
We are interested in the interview. I think at least 2 or 3 members will be able to join the interview.

**Comment by jimmychu0807** [comment]
Hi team, I received the latest update that HQ is re-considering on which team to do a short interview in the upcoming AMA session. So forget about my request here. Sorry about this.
